;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Boss.BestialLucid.Charge",DevComment="")
+GameplayTagList=(Tag="Ability.Boss.BestialLucid.Claw",DevComment="")
+GameplayTagList=(Tag="Ability.Boss.BestialLucid.Roar",DevComment="")
+GameplayTagList=(Tag="Ability.Enemy.DraugrStrike",DevComment="")
+GameplayTagList=(Tag="Cooldown.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.LightAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Lunge",DevComment="")
+GameplayTagList=(Tag="Cooldown.PrimaryFire",DevComment="")
+GameplayTagList=(Tag="Cooldown.Read",DevComment="")
+GameplayTagList=(Tag="Cooldown.Slicer",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.RampMagnitude",DevComment="")
+GameplayTagList=(Tag="Data.Selah",DevComment="")
+GameplayTagList=(Tag="Data.SuperMeter",DevComment="")
+GameplayTagList=(Tag="Event.Kill.Confirmed",DevComment="")
+GameplayTagList=(Tag="Event.Montage.HitWindow.Open",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Ability1",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Ability2",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Ability3",DevComment="")
+GameplayTagList=(Tag="Input.Ability.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Input.Ability.LightAttack",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Melee",DevComment="")
+GameplayTagList=(Tag="Input.Ability.PrimaryFire",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Reload",DevComment="")
+GameplayTagList=(Tag="Input.Ability.SuperAbility",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.InCombat",DevComment="")
+GameplayTagList=(Tag="State.Reckoning",DevComment="")
+GameplayTagList=(Tag="State.Staggered",DevComment="")
+GameplayTagList=(Tag="State.Stunned",DevComment="")

