;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Enemy.DraugrStrike",DevComment="")
+GameplayTagList=(Tag="Cooldown.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.LightAttack",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Selah",DevComment="")
+GameplayTagList=(Tag="Event.Montage.HitWindow.Open",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Ability1",DevComment="")
+GameplayTagList=(Tag="Input.Ability.HeavyAttack",DevComment="")
+GameplayTagList=(Tag="Input.Ability.LightAttack",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Melee",DevComment="")
+GameplayTagList=(Tag="Input.Ability.SuperAbility",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Stunned",DevComment="")

